### ISSUE TITLE
Could not find property 'dummyBannerAdUnitId'

### ISSUE THREAD

**Issue by otman-soulimani** [shunsugai/notification-history#59]
Could not find property 'dummyBannerAdUnitId' on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, versionNameSuffix=null, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=C:\Users\otman\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=C:\Users\otman\.android\debug.keystore}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.

**Comment by tiqniya** [comment]
add your banned id to dummybanner
